development:
  host: localhost
  database: code_campo_development
  identity_map_enabled: true

test:
  host: localhost
  database: code_campo_test
  identity_map_enabled: true

# set these environment variables on your prod server
production:
  host: localhost
  database: code_campo_production
  identity_map_enabled: true
